/** Catálogo sugerido para el admin (amenidades del inmueble / desarrollo). */
export const PRESET_AMENITIES = [
  "Alberca",
  "Gimnasio",
  "Seguridad 24/7",
  "Caseta de vigilancia",
  "Área de juegos infantiles",
  "Salón de usos múltiples",
  "Roof garden",
  "Terraza",
  "Área de asadores",
  "Spa",
  "Sauna",
  "Jacuzzi",
  "Cancha de tenis",
  "Cancha de pádel",
  "Pet park",
  "Coworking",
  "Sala de juegos",
  "Biblioteca",
  "Sala de yoga",
  "Vista panorámica",
  "Elevador",
  "Balcón",
  "Jardín",
  "Estacionamiento de visitas",
  "Sala de eventos",
  "Business center",
  "Simulador de golf",
  "Cine",
  "Ludoteca",
] as const;

export const PRESET_SERVICES = [
  "Agua potable",
  "Electricidad",
  "Gas natural",
  "Internet / Fibra óptica",
  "Drenaje",
  "Videovigilancia",
  "Mantenimiento incluido",
  "Limpieza de áreas comunes",
  "Portero",
  "Recolección de basura",
  "Alumbrado público",
  "Pavimentación",
] as const;

export const PRESET_ADDITIONAL_FEATURES = [
  "A estrenar",
  "Iluminación natural",
  "Amueblado",
  "Semi amueblado",
  "Vista al parque",
  "Esquina",
  "Penthouse",
  "Doble altura",
  "Bodega",
  "Cuarto de servicio",
  "Roof privado",
  "Acepta mascotas",
] as const;
